import {
  LinkedinIcon,
  Github,
  Twitter,
  Facebook,
  Instagram,
  Youtube,
  // Globe,
  // Mail,
  // Phone,
  // MapPin,
  // Calendar,
  // Briefcase,
  // School,
  // Award,
  // BookOpen,
  // Code2,
  // Languages,
  Link as LinkIcon,
} from "lucide-react";

export const socialMediaOptions = [
  { value: "linkedin", label: "LinkedIn", icon: LinkedinIcon },
  { value: "github", label: "GitHub", icon: Github },
  { value: "twitter", label: "Twitter", icon: Twitter },
  { value: "facebook", label: "Facebook", icon: Facebook },
  { value: "instagram", label: "Instagram", icon: Instagram },
  { value: "youtube", label: "YouTube", icon: Youtube },
  { value: "other", label: "Other", icon: LinkIcon },
  // { value: "email", label: "Email", icon: Mail },
  // { value: "phone", label: "Phone", icon: Phone },
  // { value: "location", label: "Location", icon: MapPin },
  // { value: "birthday", label: "Birthday", icon: Calendar },
  // { value: "work", label: "Work", icon: Briefcase },
  // { value: "education", label: "Education", icon: School },
  // { value: "award", label: "Award", icon: Award },
  // { value: "blog", label: "Blog", icon: BookOpen },
  // { value: "portfolio", label: "Portfolio", icon: Code2 },
  // { value: "language", label: "Language", icon: Languages },
];