import { DropdownOption } from "interfaces/dropdown";

export const CountriesOptions: DropdownOption[] = [
    { label: "Albania", value: "AL", iconCode: "AL" },
    { label: "Andorra", value: "AD", iconCode: "AD" },
    { label: "Austria", value: "AT", iconCode: "AT" },
    { label: "Belarus", value: "BY", iconCode: "BY" },
    { label: "Belgium", value: "BE", iconCode: "BE" },
    { label: "Bosnia and Herzegovina", value: "BA", iconCode: "BA" },
    { label: "Bulgaria", value: "BG", iconCode: "BG" },
    { label: "Croatia", value: "HR", iconCode: "HR" },
    { label: "Czech Republic", value: "CZ", iconCode: "CZ" },
    { label: "Denmark", value: "DK", iconCode: "DK" },
    { label: "Estonia", value: "EE", iconCode: "EE" },
    { label: "Finland", value: "FI", iconCode: "FI" },
    { label: "France", value: "FR", iconCode: "FR" },
    { label: "Germany", value: "DE", iconCode: "DE" },
    { label: "Greece", value: "GR", iconCode: "GR" },
    { label: "Great Britain", value: "GB", iconCode: "GB" },
    { label: "Hungary", value: "HU", iconCode: "HU" },
    { label: "Iceland", value: "IS", iconCode: "IS" },
    { label: "Ireland", value: "IE", iconCode: "IE" },
    { label: "Italy", value: "IT", iconCode: "IT" },
    { label: "Latvia", value: "LV", iconCode: "LV" },
    { label: "Liechtenstein", value: "LI", iconCode: "LI" },
    { label: "Lithuania", value: "LT", iconCode: "LT" },
    { label: "Luxembourg", value: "LU", iconCode: "LU" },
    { label: "Malta", value: "MT", iconCode: "MT" },
    { label: "Moldova", value: "MD", iconCode: "MD" },
    { label: "Monaco", value: "MC", iconCode: "MC" },
    { label: "Montenegro", value: "ME", iconCode: "ME" },
    { label: "Netherlands", value: "NL", iconCode: "NL" },
    { label: "North Macedonia", value: "MK", iconCode: "MK" },
    { label: "Norway", value: "NO", iconCode: "NO" },
    { label: "Poland", value: "PL", iconCode: "PL" },
    { label: "Portugal", value: "PT", iconCode: "PT" },
    { label: "Romania", value: "RO", iconCode: "RO" },
    { label: "Russia", value: "RU", iconCode: "RU" },
    { label: "San Marino", value: "SM", iconCode: "SM" },
    { label: "Serbia", value: "RS", iconCode: "RS" },
    { label: "Slovakia", value: "SK", iconCode: "SK" },
    { label: "Slovenia", value: "SI", iconCode: "SI" },
    { label: "Spain", value: "ES", iconCode: "ES" },
    { label: "Sweden", value: "SE", iconCode: "SE" },
    { label: "Switzerland", value: "CH", iconCode: "CH" },
    { label: "Ukraine", value: "UA", iconCode: "UA" },
    { label: "United Kingdom", value: "GB", iconCode: "GB" },
    { label: "Vatican City", value: "VA", iconCode: "VA" },
];

// export const CountryCodes = Countries.map((country) => country.value) as [string, ...string[]];