import { DropdownOption } from "interfaces/dropdown";

export const LanguagesOptions: DropdownOption[] = [
    { label: "Albanian", value: "AL", iconCode: "AL" },
    { label: "Catalan", value: "AD", iconCode: "AD" },
    { label: "German", value: "AT", iconCode: "AT" },
    { label: "Belarusian", value: "BY", iconCode: "BY" },
    { label: "Dutch", value: "BE", iconCode: "BE" },
    { label: "Bosnian", value: "BA", iconCode: "BA" },
    { label: "Bulgarian", value: "BG", iconCode: "BG" },
    { label: "Croatian", value: "HR", iconCode: "HR" },
    { label: "Czech", value: "CZ", iconCode: "CZ" },
    { label: "Danish", value: "DK", iconCode: "DK" },
    { label: "Estonian", value: "EE", iconCode: "EE" },
    { label: "Finnish", value: "FI", iconCode: "FI" },
    { label: "French", value: "FR", iconCode: "FR" },
    { label: "German", value: "DE", iconCode: "DE" },
    { label: "Greek", value: "GR", iconCode: "GR" },
    { label: "Hungarian", value: "HU", iconCode: "HU" },
    { label: "Icelandic", value: "IS", iconCode: "IS" },
    { label: "English", value: "IE", iconCode: "IE" },
    { label: "Italian", value: "IT", iconCode: "IT" },
    { label: "Latvian", value: "LV", iconCode: "LV" },
    { label: "German", value: "LI", iconCode: "LI" },
    { label: "Lithuanian", value: "LT", iconCode: "LT" },
    { label: "Luxembourgish", value: "LU", iconCode: "LU" },
    { label: "Maltese", value: "MT", iconCode: "MT" },
    { label: "Romanian", value: "MD", iconCode: "MD" },
    { label: "French", value: "MC", iconCode: "MC" },
    { label: "Montenegrin", value: "ME", iconCode: "ME" },
    { label: "Dutch", value: "NL", iconCode: "NL" },
    { label: "Macedonian", value: "MK", iconCode: "MK" },
    { label: "Norwegian", value: "NO", iconCode: "NO" },
    { label: "Polish", value: "PL", iconCode: "PL" },
    { label: "Portuguese", value: "PT", iconCode: "PT" },
    { label: "Romanian", value: "RO", iconCode: "RO" },
    { label: "Russian", value: "RU", iconCode: "RU" },
    { label: "Italian", value: "SM", iconCode: "SM" },
    { label: "Serbian", value: "RS", iconCode: "RS" },
    { label: "Slovak", value: "SK", iconCode: "SK" },
    { label: "Slovenian", value: "SI", iconCode: "SI" },
    { label: "Spanish", value: "ES", iconCode: "ES" },
    { label: "Swedish", value: "SE", iconCode: "SE" },
    { label: "German", value: "CH", iconCode: "CH" },
    { label: "Ukrainian", value: "UA", iconCode: "UA" },
    { label: "English", value: "GB", iconCode: "GB" },
    { label: "Italian", value: "VA", iconCode: "VA" }
];