import { DropdownOption } from "interfaces/dropdown";

export const SkillOptions: DropdownOption[] = [
    { value: 'react', label: 'React' },
    { value: 'javascript', label: 'JavaScript' },
    { value: 'typescript', label: 'TypeScript' },
    { value: 'nodejs', label: 'Node.js' },
    { value: 'python', label: 'Python' },
    { value: 'java', label: 'Java' },
    { value: 'cpp', label: 'C++' },
    { value: 'csharp', label: 'C#' },
    { value: 'php', label: 'PHP' },
    { value: 'ruby', label: 'Ruby' },
    { value: 'swift', label: 'Swift' },
    { value: 'kotlin', label: 'Kotlin' },
    { value: 'go', label: 'Go' },
    { value: 'rust', label: 'Rust' },
    { value: 'html', label: 'HTML' },
    { value: 'css', label: 'CSS' },
    { value: 'sass', label: 'SASS' },
    { value: 'nextjs', label: 'Next.js' },
    { value: 'vue', label: 'Vue.js' },
    { value: 'angular', label: 'Angular' },
    { value: 'redux', label: 'Redux' },
    { value: 'graphql', label: 'GraphQL' },
    { value: 'webpack', label: 'Webpack' },
    { value: 'sql', label: 'SQL' },
    { value: 'mongodb', label: 'MongoDB' },
    { value: 'postgresql', label: 'PostgreSQL' },
    { value: 'mysql', label: 'MySQL' },
    { value: 'redis', label: 'Redis' },
    { value: 'elasticsearch', label: 'Elasticsearch' },
    { value: 'docker', label: 'Docker' },
    { value: 'kubernetes', label: 'Kubernetes' },
    { value: 'aws', label: 'AWS' },
    { value: 'azure', label: 'Azure' },
    { value: 'gcp', label: 'Google Cloud' },
    { value: 'ci_cd', label: 'CI/CD' },
    { value: 'terraform', label: 'Terraform' },
    { value: 'git', label: 'Git' },
    { value: 'github', label: 'GitHub' },
    { value: 'gitlab', label: 'GitLab' },
    { value: 'jira', label: 'Jira' },
    { value: 'confluence', label: 'Confluence' },
    { value: 'testing', label: 'Testing' },
    { value: 'jest', label: 'Jest' },
    { value: 'cypress', label: 'Cypress' },
    { value: 'selenium', label: 'Selenium' },
    { value: 'communication', label: 'Communication' },
    { value: 'leadership', label: 'Leadership' },
    { value: 'problem_solving', label: 'Problem Solving' },
    { value: 'teamwork', label: 'Teamwork' },
    { value: 'time_management', label: 'Time Management' },
    { value: 'adaptability', label: 'Adaptability' },
    { value: 'critical_thinking', label: 'Critical Thinking' },
    { value: 'project_management', label: 'Project Management' },
    { value: 'mentoring', label: 'Mentoring' },
    { value: 'negotiation', label: 'Negotiation' },
    { value: 'machine_learning', label: 'Machine Learning' },
    { value: 'data_analysis', label: 'Data Analysis' },
    { value: 'blockchain', label: 'Blockchain' },
    { value: 'security', label: 'Security' },
    { value: 'networking', label: 'Networking' },
    { value: 'linux', label: 'Linux' },
    { value: 'agile', label: 'Agile' },
    { value: 'scrum', label: 'Scrum' },
];

export const SkillLevelOptions: DropdownOption[] = [
    { value: 'beginner', label: 'Beginner' },
    { value: 'intermediate', label: 'Intermediate' },
    { value: 'expert', label: 'Expert' },
];

// export const SkillTypeCodes = SkillOptions.map((skill) => skill.value) as [string, ...string[]];

// export const SkillLevelCodes = SkillLevelOptions.map((skill) => skill.value) as [string, ...string[]];
